version: "3.9"
services:
  fb:
    image: ol4:latest
    build: .
    command: python3 ib_realtime_18_collector.py config/config-fb.json 
#   restart: always
    user: "${UID}:${GID}"
    volumes:
      - ./IBdata:/IBapp/IBdata
      - ./logs:/logs
      -  ~/.aws/:/opt/app-root/src/.aws
    network_mode: "host"
  aapl:
    image: ol4:latest
    command: python3 ib_realtime_18_collector.py config/config-aapl.json
#   restart: always
    user: "${UID}:${GID}"
    volumes:
      - ./IBdata:/IBapp/IBdata
      - ./logs:/logs
      -  ~/.aws/:/opt/app-root/src/.aws
    network_mode: "host"
