version: "3.9"
services:
  fb:
    image: ol4:latest
    command: python3 ib_realtime_18.py config/config-fb.json >> /logs/fb_log
#   restart: always
    volumes:
      - ./IBdata:/IBapp/IBdata
      - ./logs:/logs
      -  ~/.aws/:/opt/app-root/src/.aws
    network_mode: "host"
  aapl:
    image: ol4:latest
    command: python3 ib_realtime_18.py config/config-aapl.json >> /logs/aapl_log
#   restart: always
    volumes:
      - ./IBdata:/IBapp/IBdata
      - ./logs:/logs
      -  ~/.aws/:/opt/app-root/src/.aws
    network_mode: "host"
